name: TulingRobot
main: net.lamgc.TulingPlugin.PluginMain
version: 1.1.6
depend: [Vault]
author: LamGC
commands:
     robot:
          description: 与机器人聊天233
          usage: /robot [Message(消息)]
          permission: TulingRobot.Robot
          permission-message: 嘿！你还没有与机器人聊天的权限呢！快向OP申请获得权限吧！
     setrobot:
               description: 修改机器人相关设置
               usage: /setrobot [Option(选项)/help] <args(参数)...>
               permission: TulingRobot.setRobot
               permission-message: 你不是我的Master！
permissions:
     TulingRobot.Robot:
               default: true
     TulingRobot.setRobot:
               default: op
